name: Deploy TaskFlow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: my-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install system dependencies for SQLite
        run: sudo apt-get update && sudo apt-get install -y build-essential libsqlite3-dev

      - name: Install Node dependencies
        run: npm install

      - name: Create SQLite databases
        run: |
          touch database.db
          touch sessions.db

      - name: Start the server (for test purposes)
        run: node server.js
