name: Deploy TaskFlow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set working directory to my-app
        run: cd my-app

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd my-app
          npm install

      - name: Create SQLite databases
        run: |
          cd my-app
          touch database.db
          touch sessions.db

      - name: Run Server
        run: |
          cd my-app
          node server.js
